repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0  # use latest Black version
    hooks:
      - id: black
        language_version: python3

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.0   # latest stable flake8
  #   hooks:
  #     - id: flake8
