services:
  db:
    image: postgres:14-alpine
    container_name: db-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: courtconnect-backend:1.0.0
    container_name: backend-django
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: courtconnect-frontend:1.0.0
    container_name: frontend-nextjs
    command: npm run build && next start
    volumes:
      - ./frontend:/app
      - /app/node_modules # This is to prevent host node_modules from being mounted
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
